name: sav
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
#  firebase_core: ^0.5.2+1
#  cloud_firestore: ^0.14.3+1
#  firebase_auth: ^0.18.3+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  carousel_slider: ^2.3.1
  cached_network_image: ^2.3.3
  flutter_spinkit: ^4.1.2+1
  provider: ^4.3.2+2
  flutter_staggered_animations: ^0.1.2
  flutter_typeahead: ^1.8.8
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.12+4
  animated_icon_button: ^0.3.0
  auto_size_text: ^2.1.0
#  keyboard_visibility: ^0.5.6
  country_pickers: ^1.3.0
  argon_buttons_flutter: ^1.0.6
  pin_entry_text_field: ^0.1.4
  flare_flutter: ^2.0.6
  url_launcher: ^5.7.10
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.1.0
  image_picker: ^0.6.7+14
  printing: ^3.7.1
  fluttertoast: ^7.1.5
#  esc_pos_bluetooth: ^0.2.8
#  flutter_bluetooth_basic: ^0.1.5
  intl: ^0.16.1
#  esc_pos_printer: ^2.1.2
  blue_thermal_printer: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/vegetables/
    - assets/flare/