name: sav
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  firebase_core: ^1.6.0
  cloud_firestore: ^2.5.1
  firebase_auth: ^3.1.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  flutter_spinkit: ^5.0.0
  provider: ^6.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_typeahead: ^3.2.0
  shared_preferences: ^2.0.7
  animated_icon_button: ^1.0.2
  auto_size_text: ^3.0.0-nullsafety.0
#  keyboard_visibility: ^0.5.6
  country_pickers: ^2.0.0
  argon_buttons_flutter: ^1.1.0
  flare_flutter: ^3.0.2
  url_launcher: ^6.0.9
  firebase_storage: ^10.0.3
  image_picker: ^0.8.3+3
#  printing: ^5.5.0
  fluttertoast: ^8.0.8
  flutter_local_notifications: ^8.1.1+1
  file_picker: ^4.0.0

  #  esc_pos_bluetooth: ^0.2.8
#  flutter_bluetooth_basic: ^0.1.5
  intl: ^0.17.0
#  esc_pos_printer: ^2.1.2
  blue_thermal_printer: ^1.1.4
  firebase_messaging:  ^10.0.4
#
#  modal_progress_hud: ^0.1.3
#  pin_entry_text_field: ^0.1.4
#


dev_dependencies:
  flutter_test:
    sdk: flutter





flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/vegetables/
    - assets/flare/